### ISSUE TITLE
Make a Dockerize

### ISSUE THREAD

**Issue by KimPig** [h00z3x/Lost-Music-V2#1]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Like lavamusic, if you make it into a docker image, I thnk it will be very easy to use.

**Comment by h00z3x** [comment]
It was my first time using docker. I created a Dockerfile (It isn't as configurable as LavaMusic though...). I haven't tested it completely about .env and stuffs. (also sorry about being 2 weeks late...)

I hope it works.
You can build the docker image and run it. 

Thanks for your suggestion!

**Comment by h00z3x** [comment]
No response was received.
And also I added the docker file and it works on my machine so lets call it a day...
